name: bert_ner_inference
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.7 
  - pytorch=1.6.0=py3.7_0
 - pip:
    - numpy==1.19.5
    - pandas==1.2.3
    - tokenizers==0.10.2
    - torchtext==0.7.0
    - transformers==4.6.1
